"""create event_type and booking tables

Revision ID: 0068a2c6b49d
Revises: 
Create Date: 2026-06-01 23:31:15.870295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0068a2c6b49d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_time_range', 'booking', ['start_time', 'end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_time_range', table_name='booking')
    op.drop_table('booking')
    op.drop_table('event_type')
    # ### end Alembic commands ###